"""Validated compute-side launcher, container and temporary workspace composition."""

import re
import shlex
from pathlib import PurePosixPath


def absolute(value, label):
    if (not isinstance(value, str) or not value.startswith('/')
            or any(c in value for c in '\x00\r\n') or '..' in PurePosixPath(value).parts):
        raise ValueError(f'{label} must be a remote absolute path without traversal')
    return value


def execution(spec, scheduler, resources, command):
    from .scripts import line_value
    normalized, setup, warnings = {}, [], []
    dependencies = spec.get('remote_dependencies', [])
    if not isinstance(dependencies, list):
        raise ValueError('remote_dependencies must be a list')
    for item in dependencies:
        if not isinstance(item, dict) or set(item) != {'path', 'kind'}:
            raise ValueError('remote dependency requires path and kind')
        path = absolute(item['path'], 'dependency path')
        if not isinstance(item['kind'], str):
            raise ValueError('dependency kind must be a string')
        flag = {'file': '-f', 'directory': '-d', 'executable': '-x'}.get(item['kind'])
        if flag is None:
            raise ValueError('dependency kind must be file, directory or executable')
        setup.append(f'test {flag} {shlex.quote(path)}')
        setup.append(f'test -r {shlex.quote(path)}')
    normalized['remote_dependencies'] = dependencies
    argv = list(command)
    container = spec.get('container')
    if container is not None:
        if not isinstance(container, dict) or set(container) - {'runtime', 'image', 'binds', 'gpu'}:
            raise ValueError('container accepts runtime, image, binds and gpu')
        runtime = container.get('runtime', 'apptainer')
        if runtime not in ('apptainer', 'singularity'):
            raise ValueError('container runtime must be apptainer or singularity')
        image = absolute(container.get('image'), 'container image')
        binds = container.get('binds', [])
        if not isinstance(binds, list):
            raise ValueError('container binds must be a list')
        prefix = [runtime, 'exec', '--no-eval']
        setup.append('case "$PWD" in *:*|*,*) printf "%s\\n" "Container cwd cannot contain colon or comma" >&2; exit 2;; esac')
        env_prefix = 'APPTAINERENV_' if runtime == 'apptainer' else 'SINGULARITYENV_'
        for name, value in spec.get('environment', {}).items():
            # Prefix variables override image ENV without --env comma-list ambiguity.
            setup.append('export ' + env_prefix + name + '=' + shlex.quote(value))
        if ':' in image or ',' in image:
            raise ValueError('image must be a local remote file path, not a URI')
        for bind in binds:
            if not isinstance(bind, dict) or set(bind) - {'source', 'destination', 'read_only'}:
                raise ValueError('bind accepts source, destination, read_only')
            source = absolute(bind.get('source'), 'bind source')
            destination = absolute(bind.get('destination'), 'bind destination')
            if ':' in source + destination or ',' in source + destination:
                raise ValueError('bind paths cannot contain colon or comma')
            readonly = bind.get('read_only', True)
            if type(readonly) is not bool:
                raise ValueError('bind read_only must be boolean')
            setup.append('test -r ' + shlex.quote(source))
            prefix += ['--bind', f'{source}:{destination}:{"ro" if readonly else "rw"}']
        gpu = container.get('gpu')
        if gpu not in (None, 'nv', 'rocm'):
            raise ValueError('container gpu must be nv or rocm')
        if gpu:
            if not (resources.slurm_gres or resources.slurm_gpus_per_task or resources.lsf_gpu):
                raise ValueError('container GPU passthrough requires explicit scheduler GPU resources')
            prefix.append('--' + gpu)
        setup.append('test -r ' + shlex.quote(image))
        # Dynamic PWD is generated by us, never supplied as shell code in the spec.
        argv = prefix + [image] + argv
        normalized['container'] = {**container, 'runtime': runtime, 'binds': binds, 'gpu': gpu}
        warnings.append('Container image and remote binds are trusted dependencies, not uploaded inputs; MPI ABI must match the site.')
    launcher = spec.get('launcher')
    if resources.tasks > 1 and launcher is None:
        raise ValueError('multiple tasks require an explicit launcher')
    launcher_prefix = []
    if launcher is not None:
        if not isinstance(launcher, dict) or set(launcher) - {'kind', 'arguments'}:
            raise ValueError('launcher accepts kind and arguments')
        kind = launcher.get('kind')
        arguments = launcher.get('arguments', [])
        if kind not in ('srun', 'mpirun', 'mpiexec') or not isinstance(arguments, list):
            raise ValueError('launcher kind must be srun, mpirun or mpiexec with argv arguments')
        for arg in arguments:
            line_value(arg, 'launcher argument')
            if re.match(r'^(-n(?:\d|=|$)|-np(?:\d|=|$)|-c(?:\d|=|$)|-N(?:\d|=|$)|--?(?:ntasks|np|n|nodes|cpus-per-task|ntasks-per-node|npernode|pernode|app|configfile)(?:=|$))', arg):
                raise ValueError('launcher task/CPU/node counts are generated from resources')
            if arg in ('--', ':'):
                raise ValueError('launcher arguments cannot introduce another application')
        # Only supported options can be forwarded, so aliases/abbreviations cannot
        # silently replace our generated process count or select a multi-app config.
        option_arity = ({'--mpi': 1, '--cpu-bind': 1, '--distribution': 1, '--hint': 1,
                         '--label': 0, '--unbuffered': 0, '--exclusive': 0,
                         '--kill-on-bad-exit': 1} if kind == 'srun' else
                        {'--map-by': 1, '--bind-to': 1, '--rank-by': 1, '--mca': 2,
                         '--host': 1, '--hostfile': 1, '--oversubscribe': 0,
                         '-bootstrap': 1, '-bind-to': 1, '-hostfile': 1,
                         '-genv': 2, '-env': 2})
        index = 0
        while index < len(arguments):
            option, equal, value = arguments[index].partition('=')
            if option not in option_arity:
                raise ValueError(f'unsupported launcher option {option}; count aliases and arbitrary flags are not forwarded')
            count = option_arity[option]
            if equal:
                if count != 1 or not value:
                    raise ValueError('invalid launcher option value')
                values = [value]
                index += 1
            else:
                values = arguments[index + 1:index + 1 + count]
                if len(values) != count or any(v.startswith('-') for v in values):
                    raise ValueError('missing launcher option values')
                index += 1 + count
            if option == '--map-by':
                cores = re.search(r'(?:^|:)PE=(\d+)(?:$|:)', values[0], re.I)
                if cores and int(cores[1]) != resources.cpus:
                    raise ValueError('MPI map-by PE must equal cpus per task')
                ranks = re.search(r'(?:^|:)ppr:(\d+):node(?:$|:)', values[0], re.I)
                if ranks and int(ranks[1]) != resources.tasks_per_node:
                    raise ValueError('MPI ppr ranks per node must equal explicit tasks_per_node')
        if kind == 'srun':
            if scheduler != 'slurm':
                raise ValueError('srun requires Slurm')
            launcher_prefix = ['srun', f'--ntasks={resources.tasks}', f'--cpus-per-task={resources.cpus}']
        else:
            launcher_prefix = [kind, '-np' if kind == 'mpirun' else '-n', str(resources.tasks)]
            warnings.append('MPI host discovery, process binding and bootstrap must be configured for the target site; allocation alone does not launch ranks correctly.')
        launcher_prefix += arguments
        normalized['launcher'] = {'kind': kind, 'arguments': arguments}
    # Insert runtime-generated bind immediately before the image; preserve argv quoting.
    if container is not None:
        image_index = len(argv) - len(command) - 1
        invocation = (shlex.join(launcher_prefix + argv[:image_index])
                      + ' --bind "$PWD:$PWD:rw" --pwd "$PWD" '
                      + shlex.join(argv[image_index:]))
    else:
        invocation = shlex.join(launcher_prefix + argv)
    scratch = spec.get('scratch')
    if scratch is not None:
        if not isinstance(scratch, dict) or set(scratch) - {'root', 'environment_variable', 'cleanup'}:
            raise ValueError('scratch accepts root, environment_variable and cleanup')
        if resources.nodes not in (None, 1) or resources.tasks_per_node and resources.tasks > resources.tasks_per_node:
            raise ValueError('scratch supports single-node jobs only; multi-node temporary storage needs a site-specific strategy')
        if scheduler == 'lsf' and resources.tasks > 1 and resources.tasks_per_node is None and resources.nodes != 1:
            raise ValueError('LSF scratch requires a single-host allocation')
        root = absolute(scratch.get('root'), 'scratch root')
        if container is not None and any(char in root for char in ':,'):
            raise ValueError('container scratch root cannot contain colon or comma')
        variable = scratch.get('environment_variable', 'TMPDIR')
        if (not isinstance(variable, str) or not re.fullmatch('[A-Za-z_][A-Za-z0-9_]*', variable)
                or variable in {'PATH', 'HOME', 'PWD', 'SHELL', 'BASH_ENV', 'ENV', 'LD_PRELOAD', 'EUID', 'UID', 'PPID', 'BASHOPTS', 'SHELLOPTS', 'BASH_VERSION', 'BASH_VERSINFO'}
                or variable.startswith('HPC_MCP_') or variable.startswith('hpc_mcp_')):
            raise ValueError('scratch environment_variable must be a non-reserved variable')
        cleanup = scratch.get('cleanup', True)
        if type(cleanup) is not bool:
            raise ValueError('scratch cleanup must be boolean')
        if variable in spec.get('environment', {}):
            raise ValueError('scratch variable conflicts with environment')
        setup += ['hpc_mcp_scratch=$(mktemp -d -- ' + shlex.quote(root.rstrip('/') + '/hpc-mcp.XXXXXXXXXX') + ')',
                  f'export {variable}="$hpc_mcp_scratch"']
        if cleanup:
            setup += ["trap 'hpc_mcp_rc=$?; trap - EXIT; rm -rf -- \"$hpc_mcp_scratch\" || true; exit \"$hpc_mcp_rc\"' EXIT"]
        if container is not None:
            # Also mount the newly created scratch, while retaining the run cwd for outputs.
            setup.append('export ' + env_prefix + variable + '="$hpc_mcp_scratch"')
            invocation = invocation.replace(' --pwd "$PWD" ', ' --bind "$hpc_mcp_scratch:$hpc_mcp_scratch:rw" --pwd "$PWD" ')
        normalized['scratch'] = {'root': root, 'environment_variable': variable, 'cleanup': cleanup}
        warnings.append('Scratch stays separate from the run directory. Only explicitly written run outputs are synced; abrupt node loss may leave scratch behind.')
    if dependencies:
        warnings.append('Dependency checks run on the batch host; they do not verify availability on every MPI node.')
    return setup, invocation, normalized, warnings, scratch is not None
