#BSUB -J water
#BSUB -q Gaussian
#BSUB -n 24
#BSUB -R span[ptile=24]
#BSUB -o water-%J.out
#BSUB -x
#BSUB -m node01
#BSUB -R "select[hname!='node02' && hname!='node03']"

export g16root=/share/home/ylzhao/software/g16_c02
. /share/home/ylzhao/software/g16_c02/g16/bsd/g16.profile
export GAUSS_SCRDIR=/scratch/scr/$USER/$LSB_JOBID
mkdir -p $GAUSS_SCRDIR

ORIG_DIR="$PWD"
cd "/tmp/reference-run"
echo 'Job started at' `date`
echo 'Processing: water.gjf'
/share/home/ylzhao/software/g16_c02/g16/g16 < "water.gjf" > "water.log"

rm -rf $GAUSS_SCRDIR
echo 'Job finished at' `date`
cd "$ORIG_DIR"