#BSUB -J vasp
#BSUB -q xppn2
#BSUB -R span[ptile=28]
#BSUB -n 112
#BSUB -o vasp-%J.out
source /share/apps/intel2020u4/parallel_studio_xe_2020/psxevars.sh  >/dev/null 2>&1
BIN_DIR=/apps/vasp/bin
VASP_RUNDIR=`pwd`
cd $VASP_RUNDIR
ln -s $BIN_DIR/vdw_kernel.bindat $VASP_RUNDIR/vdw_kernel.bindat
ln -s $BIN_DIR/vdw_kernel.bindat.big_endian $VASP_RUNDIR/vdw_kernel.big_endian

mpirun -bootstrap lsf $BIN_DIR/vasp621_std_AVX512_mkl >log.out 2>&1 
