#BSUB -J vasp
#BSUB -q xp40mc12
#BSUB -R span[ptile=28]
#BSUB -n 112
#BSUB -o vasp-%J.out
source /share/apps/intel/parallel_studio_xe_2015/psxevars.sh >/dev/null 2>&1 
MPI_HOME=/share/apps/intel/impi/5.0.3.048
BIN_DIR=/apps/vasp/bin
VASP_RUNDIR=`pwd`
cd $VASP_RUNDIR
ln -s $BIN_DIR/vdw_kernel.bindat $VASP_RUNDIR/vdw_kernel.bindat
ln -s $BIN_DIR/vdw_kernel.bindat.big_endian $VASP_RUNDIR/vdw_kernel.big_endian

mpirun -bootstrap lsf $BIN_DIR/vasp544_std_OPTCELL >log.out 2>&1 
