#!/share/apps/Python/Anaconda2/bin/python
##!/share/apps/soft/Python-2.7.11/python
#----/usr/bin/env python

import sys,os
import time
import argparse

#global node_cores
node_cores=28
CURDIR = os.getcwd()
VASP_LSF = CURDIR + '/vasp.lsf'
BIN_DIR = '/apps/vasp/bin'

def GetCurTime():
    '''
    Return current system time at format "MMDDYYHHMM"
    '''
    return time.strftime("%m%d%y%H%M",time.localtime(time.time()))


def cr_vasp_lsf(args):
    global BIN_DIR
    line='#BSUB -J ' + args.Jobname + '\n'
    line=line + '#BSUB -q ' + args.Queue + '\n'
    line=line + '#BSUB -R ' + 'span[ptile=' + str(node_cores) + ']\n'
    line=line + '#BSUB -n ' + str(args.Node_Number * node_cores) + '\n'
    line=line + '#BSUB -o ' + args.Jobname + '-%J.out\n'
    if args.MPI_version == '2018':
    # line=line + 'source /share/apps/intel/parallel_studio_xe_2015/psxevars.sh >/dev/null 2>&1 \n'
        line=line + 'source /share/apps/intel_ips_xe_2018u3/parallel_studio_xe_2018/psxevars.sh >/dev/null 2>&1 \n'
    # line=line + 'MPI_HOME=/share/apps/intel/impi/5.0.3.048\n'
        line=line + 'MPI_HOME=/share/apps/intel_ips_xe_2018u3/impi/2018.3.222\n'
    elif args.MPI_version == '2015':
        line=line + 'source /share/apps/intel/parallel_studio_xe_2015/psxevars.sh >/dev/null 2>&1 \n'
        line=line + 'MPI_HOME=/share/apps/intel/impi/5.0.3.048\n'
    elif args.MPI_version == '2019':
        line=line + 'source /share/apps/Intel/intel2019u5/parallel_studio_xe_2019/psxevars.sh >/dev/null 2>&1\n'
        line=line + 'MPI_HOME=/share/apps/Intel/intel2019u5/impi/2019.5.281/intel64/bin\n'

    else:
        #line=line + 'export PATH=/share/apps/scripts:/share/apps/intel/impi/5.0.3.048/bin64 \n'
        #line=line + 'export LD_LIBRARY_PATH=/share/apps/intel/mkl/lib/intel64 \n'
        #line=line + 'MPI_HOME=/share/apps/intel/impi/5.0.3.048\n'
        line=line + 'source /share/apps/intel2020u4/parallel_studio_xe_2020/psxevars.sh  >/dev/null 2>&1\n'
        #line=line + 'MPI_HOME=/share/apps/intel2020u4/intelpython3/bin\n' 
        #line=line + 'module load gcc/7.5.0\n'


    line=line + 'BIN_DIR=' + BIN_DIR + '\n'
    line=line + 'VASP_RUNDIR=`pwd`\n'
    line=line + 'cd $VASP_RUNDIR\n'
    line=line + 'ln -s $BIN_DIR/vdw_kernel.bindat $VASP_RUNDIR/vdw_kernel.bindat\n'
    line=line + 'ln -s $BIN_DIR/vdw_kernel.bindat.big_endian $VASP_RUNDIR/vdw_kernel.big_endian\n'
    line=line + '\n'
    PROG = 'vasp' + args.VASP_version + '_' + args.Program_Type
    if args.Queue not in ['xp40mc12'] :
        PROG += '_AVX512_mkl'
    if args.optcell and args.VASP_version in ['544'] :
        PROG += '_OPTCELL' 
    if args.openmp and args.VASP_version in ['620','621'] :
        PROG += '_openmp'
    if args.HDF5:
        PROG += '.hdf5'
        line=line + 'export LD_LIBRARY_PATH=/apps/Tools/HDF5/hdf5-1.12.2/lib:$LD_LIBRARY_PATH\n'
    #line=line + '$MPI_HOME/mpirun -bootstrap lsf $BIN_DIR/' + PROG + ' >log.out 2>&1 \n'
    line=line + 'mpirun -bootstrap lsf $BIN_DIR/' + PROG + ' >log.out 2>&1 \n'
    
    with open(VASP_LSF,'w') as v_lsf:
       v_lsf.write(line)
       
    
    
def main(argv = None):
    global node_cores,BIN_DIR
    argparser = argparse.ArgumentParser(description = 
    '''
	Running Vasp Program @ Xcluster  //   \n
        Version: 5.4.4   //   \t
        Compiled by Intel Compiler 2019u5 along with Intel MPI 2019.5.281 
    ''')
    argparser.add_argument('-q', dest='Queue',
                           type = str,
                           default = 'xppn2',
                           help = "Queue names: xppn1/xppn2/xp72mc10/xp36mc10; 'xppn2' is default."
                          )
    argparser.add_argument('-j', dest='Node_Number',
                           type = int,
                           default = 4,
                           help = "Node number: 1/2/3/4/8/...; '4' is default."
                          )
    argparser.add_argument('-p', dest='Core_Number',
                           type = int,
                           default = node_cores,
                           help = "Core number used per node: 1/2/3/4/8/28...; " +str(node_cores) +" is default." 
                          )
    argparser.add_argument('-m', dest='MPI_version',
                           type = str,
                           default = '2020',
                           help = "Intel MPI version 2015(5.0.3.048) / 2018 (2018.3.222 / 2019 (u5)... ). 2020 is default."
                          )
    argparser.add_argument('-v', dest='VASP_version',
                           type = str,
                           default = '621',
                           help = "VASP version 544 (5.4.4) / 620 (6.2.0) / 621 (6.2.1)... ). 621 is default."
                          )
    argparser.add_argument('--openmp', dest='openmp',#
                           action='store_true',
                           default = False,
                           help = "Use openmp or not. For vasp6 only."
                           )
    argparser.add_argument('--optcell', dest='optcell',#
                           action='store_true',
                           default = False,
                           help = "Use OPTCELL or not. For vasp544 only. see https://blog.shishiruqi.com/2019/05/05/constr/"
                           )
    argparser.add_argument('-t', dest='Program_Type',#
                           type = str,
                           default = 'std',
                           help = "Vasp program Type : std/gam/ncl. 'std' is default. VTST/beef/VASPsol/wannier90 have been included. 'beef' refers to Bayesian Error Estimation Functionals. All but 'wannier' options include the beef, VASPsol and vtst functions. PLS see http://suncat.stanford.edu/theory/software  and https://github.com/henniggroup/VASPsol for details."
                          )
    argparser.add_argument('--hdf5', dest='HDF5',#
                           action='store_true',
                           default = False,
                           help = "Compiled with HDF5, for default program type only."
                           )
    argparser.add_argument('-d', dest='Debug',#
                           action='store_true',
                           default = False,
                           help = "Print bsub file for debug."                          
                           ) 

    argparser.add_argument('Jobname',
                           type = str,
                           default = 'Test',
                           help = "Vasp Job name"
                          )
    args = argparser.parse_args()
    if args.Program_Type not in ['std','gam','ncl']:
        print("Wrong Type inputed! Pls type '-h' for detail usage.")
        sys.exit()
    if args.Queue in ['AMD', 'xp72mc10','xp36mc10','xp48mc8','xp40mc12','xp112mc7','xppn1','xppn2']:
        BIN_DIR =  '/apps/vasp/bin'
    if args.Core_Number > 192:
        print("Wrong Type inputed! -p option should be less than 112 in general. Pls type '-h' for detail usage.")
        sys.exit()
    else:
        node_cores = args.Core_Number

    cr_vasp_lsf(args)
    if args.Debug:
        output=os.system('cat ' + VASP_LSF)
    else:
        LSF_OUT= CURDIR + '/vasp_jobid'
        try:
           output=os.system('bsub < ' + VASP_LSF + ' 1> ' + LSF_OUT)
           with open(LSF_OUT,'r') as lsf_jobid:
               txt=lsf_jobid.read()
               lines = txt.split('\n')
               jobid_txt=lines[0].split()[1]
               jobid=jobid_txt[1:-1]
               jobid_filename=CURDIR + '/' + jobid + '.jobid'
               output=os.system('mv ' + LSF_OUT + ' '+ jobid_filename)
               output=os.system('cat '+ jobid_filename)
        except:
           print("Wrong options inputed! Pls type '-h' for detail usage.")

if __name__ == '__main__':
    main()

